// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyoxfHIsIIgqldbst7hKUGo2BkeYpnJuw',
    appId: '1:612231640845:android:1b2c6e9402885645686244',
    messagingSenderId: '612231640845',
    projectId: 'chat-app-84c2c',
    databaseURL: 'https://chat-app-84c2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-84c2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3F6Nq9Uj9lXCAVwZPCxMdYtRiaUtGVcg',
    appId: '1:612231640845:ios:49d1e2822164e218686244',
    messagingSenderId: '612231640845',
    projectId: 'chat-app-84c2c',
    databaseURL: 'https://chat-app-84c2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-84c2c.appspot.com',
    iosBundleId: 'com.sheikhani.communication',
  );
}
